### ISSUE TITLE
Use it with helm template

### ISSUE THREAD

**Issue by disaster37** [vivid-money/helm-plugin-render-values#4]
Hi, I try to use it with `helm template` to use it with Argocd.
It seems not working ?

Maybee i have not understand how use it. I have created a `values.yaml` on base path of my helm chart. In this, I put my standard helm values and some variables to act as `Self values rendering`. The I create a test values on tests/sample-values.yaml with some static values.

values.yaml
```yaml
labels:
  application: 'cert-manager'
  environment: ''

cert-manager:
  global:
    commonLabels:
      environment: {{ .Values.labels.environment }}
```

tests/sample-values.yaml
```yaml
labels:
  environment: test
```

To test it, I use:

```bash
helm template . -f render://tests/sample-values.yaml
```

I get somtehing like this:
```
Error: cannot load values.yaml: error converting YAML to JSON: yaml: invalid map key: map[interface {}]interface {}{".Values.labels.environment":interface {}(nil)}
```
